- _config.yml
> Updated to Rebble Name and Site

- css/common.css
To Match Panic Store:
- Changed BG
- Changed Header BG
- Changed Section BG
- Fixed Bio arrow location in 2n
> CSS Changes

- css/common.css
- Centered Bio Triangle
- Re added footer bg-color to prevent issue that @jneubrand encontered
> Minor CSS Changes

- projects.md
Updated urls to match new subdomain and vue urls.
> Updated App Store's URLs

- _posts/2018-02-02-rebble-web-services.md
- _posts/2018-02-15-rebble-web-services.md
- css/common.css
This blog post outlines our (by which I really mean "my") plans. Yell out if you disagree with anything I said!
This mentions that we will be collecting money to run the service. We still don't know what to do with any excess we might end up with, though. We should decide this before we actually collect any money.
Also please don't merge yet — I'm waiting to hear back from Dark Sky and Fitbit.
> RWS blog post

- _data/team.yml
> Fix "" bug in my profile

- _data/team.yml
I'm officially student at Vienna's technical university since October last year and I totally forgot that I had this in my bio ^^
> update my bio as I'm not in school anymore

- _data/index.yml
- _includes/siteindex.html
- _posts/2018-06-13-get-ready-to-rebble.md
This is just a brief update and a request that people go make their accounts.
> Blog post: Getting Ready for Rebble

- 404.md
- _layouts/error.html
- css/common.css
Add a 404 page similar to the one on the Rebble Store.
> Add 404 and expand-ability for other errors

- _includes/head.html
> Add theme-color metadata

- _includes/head.html
- _includes/header.html
- _includes/real_time_rebble_dark.svg
- _includes/real_time_rebble_light.svg
- _layouts/default.html
- css/svg.css
- images/real_time_rebble_dark.svg
- images/real_time_rebble_light.svg
- js/svg.js
> Close #46 new svg logos, add css and js that create a real-time clock.

- _includes/head.html
- blog/index.html
- css/common.scss
- Version CSS Files
- Add permalink to blog, with this the blog now shows as the active page when you are on it
- Re-addded missing logo scss files import needed for other RWS sites.
I'm not sure if we should fix the title of the how-to page because on the browser title it shows in all caps `HOWTO`.
> Minor fixes

- _posts/2019-07-25-its-timeline-time.md
Hey, what's all the fuss about?  Is there a new feature or something?
> It's Timeline time!

- howto.md
> Add wiki and subreddit links to the HOWTO page

- submit/index.html
- submit/main.js
Pull dev portal 1.2 into production repo.
Dev portal changes:
- Updated modal. Now tells users to email .zip rather than use discord
- Fixed image resize bug in dev portal
> Pull latest dev portal to production

- submit/index.html
- submit/main.js
Bring in the latest dev portal master to production.
Changes:
- Hide watchapp specific fields (large icon, small icon, banner) on watchface submission
- Disallow creation of .zip if type is watchapp and user hasn't provided a banner
> Update dev portal to 1.3

- _posts/2020-09-04-rebble-grants.md
We're doing what???  WE SURE ARE!
> Rebble Grants!

- submit/index.html
- submit/main.js
See https://github.com/pebble-dev/rebble-dev-portal/pull/11 for the dev portal changes this brings in
> Bump developer portal to e0a191fbce1087680364f2e5395d2378b900f5c2

- charon/index.html
Sometimes the play store opens in a new tab, and the old one stays open, I've added small styling so it doesn't look gross
> Add minor styling to charon redirect

- submit/index.html
- submit/main.js
- submit/rws.css
This introduces an new options for updating an app, and fixes one bug
See the dev portal repo for more detail
> Bump dev portal to 1.5

- submit/index.html
- submit/main.js
Minor bugfix, see dev portal repo
> Bump dev portal to 1.6

- _scss/home.scss
Fix the sticker image dimensions
> Specifiy image dimensions
